config/routes.rb
Rails.application.routes.draw do
  get 'projects/index'
  post 'projects/create'
  post 'projects/delete'

  get 'about/index'

  devise_for :users
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :require_login

  def index
    @projects = Project.all
  end

  def create
    Project.create(title: params['title'],description: params['description'],price: params['price'])
    redirect_to projects_index_path
  end

  def delete
    project_aux = Project.find(params['code'])
    project_aux.destroy
    redirect_to projects_index_path
  end

  #FILTROS
  def require_login
    if not user_signed_in?
        redirect_to new_user_session_path
    end
  end
  def require_fill

  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/about/index.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Ejemplo Clase</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li ><a href="/">Home</a></li>
        <li class="active"><a href="#">Acerca de</a></li>
        <li ><a href="<%= projects_index_path %>">Proyectos</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>

            <li><a href="<%=edit_user_registration_path %>"><span class="glyphicon glyphicon-settings"></span> Configuraciones</a></li>

             <td><%= link_to 'Cerrar Sesion', destroy_user_session_path, method: :delete,class: 'btn btn-danger' %></td>
            <% else %>
            <li><a href="<%=new_user_session_path %>"><span class="glyphicon glyphicon-log-in"></span> Ingresar</a></li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>

<div class="container-fluid text-center">
  <div class="row content">
    <div class="col-sm-2 sidenav">
      <p><a href="http://facebook.com/profile.php">Facebook</a></p>
      <p><a href="https://twitter.com/uncolombia?lang=es">Twitter</a></p>
      <p><a href="https://www.instagram.com/explore/locations/235252960/universidad-nacional-de-colombia-sede-bogota/">Instagram</a></p>
    </div>
    <div class="col-sm-8 text-left">
      <h2>El talento ‘made in Colombia' presente en el Mobile World Congress</h2>
      <p>Ocho equipos de emprendedores colombianos dicen presente en uno de los congresos más importantes de tecnología en el mundo: el Mobile World Congress, que por primera vez en su historia, abre sus puertas en San Francisco, Estados Unidos.</p>
      <p>Los jóvenes, entre los 24 y 30 años de edad, algunos recién graduados de la universidad, hablan con felicidad de lo que significa para ellos ser parte de los 1.000 expositores que conforman el congreso.</p>
      <p>Los emprendedores, que viajaron a San Francisco con ayuda de Procolombia, el MinTIC y de los ingresos obtenidos a través de sus empresas, tienen un objetivo en la feria y va más allá de conseguir financiación: “darle a conocer al mundo el talento colombiano”.</p>
      <p>Así lo aseguró Robert Parada, un emprendedor antioqueño y director de PetyApp, una aplicación que busca cambiar la forma como las personas cuidan a sus mascotas. </p>
      <p>“Nuestra aplicación conecta a dueños de mascotas con proveedores de productos y servicio para que reciban atención personalizada. Nuestros objetivos en esta feria son dos: por un lado, levantar 400.000 dólares en inversión de capital para expandir nuestro software en varias partes del mundo. Y de otro lado, es visibilizar el talento colombiano ante grandes compañías de tecnología”, agregó Parada.</p>
      <hr>
    </div>
    <div class="col-sm-2 sidenav">
      <div class="well">

            <img width="100%" height="100%" src="http://programacion.net/files/article/20151023121029_rubyrails.png" alt="">
      </div>
      <div class="well">

              <img width="100%" src="http://carrerasuniversitarias.com.co/logos/original/logo-universidad-nacional-de-colombia.png" alt="">

      </div>
    </div>
  </div>
</div>



<footer class="container-fluid text-center">
  <p>KMJMS Derechos reservados</p>
</footer>

app/views/home/index.html.erb
<style>
    /* Remove the navbar's default margin-bottom and rounded borders */
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }

    /* Add a gray background color and some padding to the footer */
    footer {
      background-color: #f2f2f2;
      padding: 25px;
    }

  .carousel-inner img {
      width: 100%; /* Set width to 100% */
      margin: auto;
      min-height:200px;
  }

  /* Hide the carousel text when the screen is less than 600 pixels wide */
  @media (max-width: 600px) {
    .carousel-caption {
      display: none;
    }
  }
  </style>

  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Ejemplo Clase</a>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
          <li class="active"><a href="/">Home</a></li>
          <li><a href="<%= about_index_path %>">Acerca de</a></li>
          <li><a href="<%= projects_index_path %>">Proyectos</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>

              <li><a href="<%=edit_user_registration_path %>"><span class="glyphicon glyphicon-settings"></span> Configuraciones</a></li>

               <td><%= link_to 'Cerrar Sesion', destroy_user_session_path, method: :delete,class: 'btn btn-danger' %></td>
              <% else %>
              <li><a href="<%=new_user_session_path %>"><span class="glyphicon glyphicon-log-in"></span> Ingresar</a></li>
          <% end %>

        </ul>
      </div>
    </div>
  </nav>

  <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img src="https://unsplash.it/1200/400/?random" alt="Image">
          <div class="carousel-caption">
            <h3>Sell $</h3>
            <p>Money Money.</p>
          </div>
        </div>

        <div class="item">
          <img src="https://unsplash.it/1200/400/?random" alt="Image">
          <div class="carousel-caption">
            <h3>More Sell $</h3>
            <p>Lorem ipsum...</p>
          </div>
        </div>
      </div>

      <!-- Left and right controls -->
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
  </div>

  <div class="container text-center">
    <h3>Que hacemos</h3><br>
    <div class="row">
      <div class="col-sm-4">
        <img src="https://unsplash.it/150/80/?random" class="img-responsive" style="width:100%" alt="Image">
        <p>Proyecto 1</p>
      </div>
      <div class="col-sm-4">
        <img src="https://unsplash.it/150/80/?random" class="img-responsive" style="width:100%" alt="Image">
        <p>Proyecto 2</p>
      </div>
      <div class="col-sm-4">
        <div class="well">
         <a href="<%= projects_index_path %>">
           Listar Todos los proyectos
         </a>
        </div>
        <div class="well">
          <a href="<%= about_index_path %>">
            Acerca de Nosotros
          </a>
        </div>
      </div>
    </div>
  </div><br>

  <footer class="container-fluid text-center">
    <p>KMJMS Derechos reservados</p>
  </footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClassExample</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link href='http://fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'>

  </head>

  <body>
    <%= yield %>
    <script src="/lib/jquery/jquery.min.js"></script>
    <script src="/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.13.1/jquery.validate.min.js"></script>
  </body>
</html>

app/views/projects/index.html.erb
<style>
    /* Remove the navbar's default rounded borders and increase the bottom margin */
    .navbar {
      margin-bottom: 50px;
      border-radius: 0;
    }

    /* Remove the jumbotron's default bottom margin */
     .jumbotron {
      margin-bottom: 0;
    }

    /* Add a gray background color and some padding to the footer */
    footer {
      background-color: #f2f2f2;
      padding: 25px;
    }
  </style>

  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Ejemplo Clase</a>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
          <li ><a href="/">Home</a></li>
          <li><a href="<%= about_index_path %>">Acerca de</a></li>
          <li class="active"><a href="#">Proyectos</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>

              <li><a href="<%=edit_user_registration_path %>"><span class="glyphicon glyphicon-settings"></span> Configuraciones</a></li>

               <td><%= link_to 'Cerrar Sesion', destroy_user_session_path, method: :delete,class: 'btn btn-danger' %></td>
              <% else %>
              <li><a href="<%=new_user_session_path %>"><span class="glyphicon glyphicon-log-in"></span> Ingresar</a></li>
          <% end %>

        </ul>
      </div>
    </div>
  </nav>

<% @projects.each do |pro| %>

  <div class="col-md-4">

    <div class="panel panel-primary">
      <div class="panel-heading">
        <p>
          <form action="<%= projects_delete_path %>" method="post">
              <input type="text" name="code" value="<%= pro.id %>" style = "visibility:hidden">
              <button type="submit" class="btn btn-danger pull-right" name="button">X</button>
          </form>
        </p>
        <p><%= pro.title %></p>
      </div>
      <div class="panel-body">
        <img src="http://placezombie.com/150x80 " class="img-responsive" style="width:100%" alt="Image">
        <p>Precio: <%= pro.price %></p>
      </div>
      <div class="panel-footer"><%= pro.description %></div>
    </div>
  </div>
<br>
<% end %>

<div class="row">
  <form class="" action="<%= projects_create_path %>" method="post">
    <table class="table table-bordered">
  <thead>
    <tr>
      <th>titulo</th>
      <th>Descripcion</th>
      <th>precio</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><input class="form-control" type="text" name="title" value="" required></td>
      <td><input class="form-control" type="text" name="description" value="" required></td>
      <td><input class="form-control" type="number" name="price" value="" required></td>
      <td><button  type="submit" class="btn btn-success">Guardar</button></td>
    </tr>
  </tbody>
</table>
  </form>
</div>